In [68]:
import numpy as np   # 수 연산
import pandas as pd   # 데이터분석
import matplotlib.pyplot as plt    # 시각화
import seaborn as sns   # 샘플 + 화려함

import matplotlib.font_manager as fm # 한글폰트를 쓰기 위한 방법(?)
font_name = fm.FontProperties(fname="C:/Windows/Fonts/malgun.ttf").get_name()
plt.rc("font", family=font_name)

import matplotlib as mpl
mpl.rcParams["axes.unicode_minus"] = False

import operator
from numpy import linalg

In [69]:
#머신러닝 관련(사이킷런)
import mglearn

from sklearn.model_selection import train_test_split, KFold, StratifiedKFold, cross_val_score, GridSearchCV, cross_validate
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_curve
from sklearn.metrics import precision_score, recall_score

from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler, MinMaxScaler

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Perceptron

from sklearn.svm import LinearSVR, SVR, SVC

import xgboost as xgb
from xgboost import XGBClassifier, XGBRegressor
from xgboost import plot_importance, plot_tree

from lightgbm import LGBMClassifier, LGBMRegressor
from lightgbm import plot_importance, plot_tree, plot_metric

import statsmodels.api as sm

# 구내식당 중식 인원 머신러닝

+ 1. Use train data and check performance of each algorithm
+ 2. Apply some best algorithm to test data

In [11]:
ln_train = pd.read_csv("../byun/data/lunch_df_encoding.csv", encoding="utf-8")
ln_train

,datetime,year,month,date,worker_number,real_number,vacation_number,biztrip_number,overtime_number,telecom_number,...,season_winter,weekdays_friday,weekdays_monday,weekdays_thursday,weekdays_tuesday,weekdays_wednesday,vacation_N,vacation_Y,new_lunch_N,new_lunch_Y
0,2016-02-01,2016,2,1,2601,2401,50,150,238,0,...,1,0,1,0,0,0,1,0,1,0
1,2016-02-02,2016,2,2,2601,2378,50,173,319,0,...,1,0,0,0,1,0,1,0,1,0
2,2016-02-03,2016,2,3,2601,2365,56,180,111,0,...,1,0,0,0,0,1,1,0,1,0
3,2016-02-04,2016,2,4,2601,2277,104,220,355,0,...,1,0,0,1,0,0,1,0,1,0
4,2016-02-05,2016,2,5,2601,2142,278,181,34,0,...,1,1,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,2021-01-20,2021,1,20,2983,2319,75,198,4,391,...,1,0,0,0,0,1,1,0,1,0
1201,2021-01-21,2021,1,21,2983,2309,92,231,462,351,...,1,0,0,1,0,0,1,0,1,0
1202,2021-01-22,2021,1,22,2983,2177,255,248,1,303,...,1,1,0,0,0,0,1,0,1,0
1203,2021-01-25,2021,1,25,2983,2396,107,153,616,327,...,1,0,1,0,0,0,1,0,1,0
1204,2021-01-26,2021,1,26,2983,2369,69,183,551,362,...,1,0,0,0,1,0,1,0,1,0

In [12]:
ln_train.info()
ln_train.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1205 entries, 0 to 1204
Data columns (total 31 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   datetime               1205 non-null   object
 1   year                   1205 non-null   int64
 2   month                  1205 non-null   int64
 3   date                   1205 non-null   int64
 4   worker_number          1205 non-null   int64
 5   real_number            1205 non-null   int64
 6   vacation_number        1205 non-null   int64
 7   biztrip_number         1205 non-null   int64
 8   overtime_number        1205 non-null   int64
 9   telecom_number         1205 non-null   int64
 10  temperature            1204 non-null   float64
 11  rain                   1205 non-null   float64
 12  wind                   1204 non-null   float64
 13  humidity               1205 non-null   float64
 14  discomfort_index       1204 non-null   float64
 15  perceived_temperature  1203 non-null   float64
 16  lunch_rice             1205 non-null   int64
 17  lunch_number           1205 non-null   int64
 18  season_fall            1205 non-null   int64
 19  season_spring          1205 non-null   int64
 20  season_summer          1205 non-null   int64
 21  season_winter          1205 non-null   int64
 22  weekdays_friday        1205 non-null   int64
 23  weekdays_monday        1205 non-null   int64
 24  weekdays_thursday      1205 non-null   int64
 25  weekdays_tuesday       1205 non-null   int64
 26  weekdays_wednesday     1205 non-null   int64
 27  vacation_N             1205 non-null   int64
 28  vacation_Y             1205 non-null   int64
 29  new_lunch_N            1205 non-null   int64
 30  new_lunch_Y            1205 non-null   int64
dtypes: float64(6), int64(24), object(1)
memory usage: 292.0+ KB

(1205, 31)

In [13]:
ln_train.isnull().sum() #칼럼별 결측치 수

datetime                 0
year                     0
month                    0
date                     0
worker_number            0
real_number              0
vacation_number          0
biztrip_number           0
overtime_number          0
telecom_number           0
temperature              1
rain                     0
wind                     1
humidity                 0
discomfort_index         1
perceived_temperature    2
lunch_rice               0
lunch_number             0
season_fall              0
season_spring            0
season_summer            0
season_winter            0
weekdays_friday          0
weekdays_monday          0
weekdays_thursday        0
weekdays_tuesday         0
weekdays_wednesday       0
vacation_N               0
vacation_Y               0
new_lunch_N              0
new_lunch_Y              0
dtype: int64

In [14]:
ln_train = ln_train.dropna()
ln_train

,datetime,year,month,date,worker_number,real_number,vacation_number,biztrip_number,overtime_number,telecom_number,...,season_winter,weekdays_friday,weekdays_monday,weekdays_thursday,weekdays_tuesday,weekdays_wednesday,vacation_N,vacation_Y,new_lunch_N,new_lunch_Y
0,2016-02-01,2016,2,1,2601,2401,50,150,238,0,...,1,0,1,0,0,0,1,0,1,0
1,2016-02-02,2016,2,2,2601,2378,50,173,319,0,...,1,0,0,0,1,0,1,0,1,0
2,2016-02-03,2016,2,3,2601,2365,56,180,111,0,...,1,0,0,0,0,1,1,0,1,0
3,2016-02-04,2016,2,4,2601,2277,104,220,355,0,...,1,0,0,1,0,0,1,0,1,0
4,2016-02-05,2016,2,5,2601,2142,278,181,34,0,...,1,1,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,2021-01-20,2021,1,20,2983,2319,75,198,4,391,...,1,0,0,0,0,1,1,0,1,0
1201,2021-01-21,2021,1,21,2983,2309,92,231,462,351,...,1,0,0,1,0,0,1,0,1,0
1202,2021-01-22,2021,1,22,2983,2177,255,248,1,303,...,1,1,0,0,0,0,1,0,1,0
1203,2021-01-25,2021,1,25,2983,2396,107,153,616,327,...,1,0,1,0,0,0,1,0,1,0
1204,2021-01-26,2021,1,26,2983,2369,69,183,551,362,...,1,0,0,0,1,0,1,0,1,0

## 선형회귀(일반) - train: 78.40%, test: 81.09%

In [160]:
X= ln_train.drop(columns=["datetime", "year", "month", "date", "lunch_number"], axis=1)

y = ln_train["lunch_number"]

y = y.to_numpy()
y
X.shape

(1203, 26)

In [161]:
lr = LinearRegression().fit(X, y)
print("훈련 점수 : ", lr.score(X, y))

훈련 점수 :  0.7805977851040704

In [162]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
lr = LinearRegression().fit(X_train, y_train)

In [163]:
print("훈련 점수 : ", lr.score(X_train, y_train))
print("테스트 점수 : ", lr.score(X_test, y_test))

훈련 점수 :  0.7744676393793465
테스트 점수 :  0.806340497472633

## 릿지회귀모델 - train: 78.42%, test: 80.96%

In [164]:
from sklearn.linear_model import Ridge

ridge = Ridge().fit(X_train, y_train) # Ridge(alpha=1.0) 이 디폴트

print("훈련 점수 : ", ridge.score(X_train, y_train))
print("테스트 점수 : ", ridge.score(X_test, y_test))

ridge10 = Ridge(alpha=10).fit(X_train, y_train) # Ridge(alpha=1.0) 이 디폴트

print("훈련 점수 : ", ridge10.score(X_train, y_train))
print("테스트 점수 : ", ridge10.score(X_test, y_test))


ridge01 = Ridge(alpha=0.000000001).fit(X_train, y_train) # Ridge(alpha=1.0) 이 디폴트

print("훈련 점수 : ", ridge01.score(X_train, y_train))
print("테스트 점수 : ", ridge01.score(X_test, y_test))

# Ridge: lower alpha makes greater score

훈련 점수 :  0.7745270909242273
테스트 점수 :  0.8061403993363163
훈련 점수 :  0.7738701648631143
테스트 점수 :  0.8035214948924504
훈련 점수 :  0.7745354508464001
테스트 점수 :  0.8063745910246695

## 라쏘회귀모델 - train: 78.41%, test: 80.95%

In [165]:
from sklearn.linear_model import Lasso

lasso = Lasso().fit(X_train, y_train) #Lasso(alpha=1) 디폴트

print("훈련 점수 : ", lasso.score(X_train, y_train))
print("테스트 점수 : ", lasso.score(X_test, y_test)) 

print("사용한 특성의 수 : ", np.sum(lasso.coef_ != 0)) 
lasso001 = Lasso(alpha=0.01).fit(X_train, y_train)

print("훈련 점수 : ", lasso001.score(X_train, y_train))
print("테스트 점수 : ", lasso001.score(X_test, y_test))

print("사용한 특성의 수 : ", np.sum(lasso001.coef_ != 0))

lasso00001 = Lasso(alpha=0.000000001).fit(X_train, y_train)

print("훈련 점수 : ", lasso00001.score(X_train, y_train))
print("테스트 점수 : ", lasso00001.score(X_test, y_test)) 

print("사용한 특성의 수 : ", np.sum(lasso00001.coef_ != 0))

# Lasso: lower alpha makes greater score

훈련 점수 :  0.7714674631212997
테스트 점수 :  0.7973694684460665
사용한 특성의 수 :  17
훈련 점수 :  0.7745266937934594
테스트 점수 :  0.8061964511661587
사용한 특성의 수 :  24
훈련 점수 :  0.7745286232155376
테스트 점수 :  0.8062382963215178
사용한 특성의 수 :  25

C:\Users\tagos71\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 54754.2017268613, tolerance: 4229.542462474013
  model = cd_fast.enet_coordinate_descent(
C:\Users\tagos71\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4218127.484190142, tolerance: 4229.542462474013
  model = cd_fast.enet_coordinate_descent(
C:\Users\tagos71\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4768203.756758769, tolerance: 4229.542462474013
  model = cd_fast.enet_coordinate_descent(

## SVR model - train: 77.53%, test: 80.27%

- Normal
- Kernel("linear" is best)
- StandardScaler // MinMaxScaler

In [166]:
model = SVR()  # default is rbf
model.fit(X_train, y_train)

print("학습 결과 : ", model.score(X_train, y_train))
print("테스트 결과 : ", model.score(X_test, y_test))

# Too bad

학습 결과 :  0.018797147840161066
테스트 결과 :  0.02339399967759559

In [167]:
linear_svr = SVR(kernel="linear")
linear_svr.fit(X_train, y_train)

print("학습 결과 : ", linear_svr.score(X_train, y_train))
print("테스트 결과 : ", linear_svr.score(X_test, y_test))

print('===================================================')

linear_svr = SVR(kernel="linear", C=10, gamma='scale')
linear_svr.fit(X_train, y_train)

print("학습 결과 : ", linear_svr.score(X_train, y_train))
print("테스트 결과 : ", linear_svr.score(X_test, y_test))

# Greater than previous model but it is even lower than lasso and ridge

# print('===================================================')
# polynomial_svr = SVR(kernel="poly")
# polynomial_svr.fit(X_train, y_train)

# print("학습 결과 : ", polynomial_svr.score(X_train, y_train))
# print("테스트 결과 : ", polynomial_svr.score(X_test, y_test))

학습 결과 :  0.7495449960438807
테스트 결과 :  0.7665596070491147
===================================================
학습 결과 :  0.7598425815763279
테스트 결과 :  0.7848905740807566

In [168]:
### 정규화 해보자

scaler = MinMaxScaler()
X_train_mms = scaler.fit_transform(X_train)
X_test_mms = scaler.transform(X_test)

model = SVR(kernel='linear')
model.fit(X_train_mms, y_train)

print("학습 결과 : ", model.score(X_train_mms, y_train))
print("테스트 결과 : ", model.score(X_test_mms, y_test))

## 표준화든 정규화든 크게 관계없이 성능이 비슷한 수준으로 좋아졌다

학습 결과 :  0.5543366587229037
테스트 결과 :  0.5525239990090025

In [169]:
### 표준화 해보자

scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

model = SVR(kernel='linear')
model.fit(X_train_std, y_train)

print("학습 결과 : ", model.score(X_train_std, y_train))
print("테스트 결과 : ", model.score(X_test_std, y_test))

## 표준화만 했는데도 성능이 좋아짐

학습 결과 :  0.7612846442816439
테스트 결과 :  0.7955936214049628

In [59]:
model = SVR(kernel='linear', C=10)
model.fit(X_train_std, y_train)

print("학습 결과 : ", model.score(X_train_std, y_train))
print("테스트 결과 : ", model.score(X_test_std, y_test))
print('===================================================')
model = SVR(kernel='linear', C=10, gamma='auto')
model.fit(X_train_std, y_train)

print("학습 결과 : ", model.score(X_train_std, y_train))
print("테스트 결과 : ", model.score(X_test_std, y_test))
print('===================================================')
# gamma=scale & gamma=auto are same score

학습 결과 :  0.774621434983584
테스트 결과 :  0.8038651022229766
===================================================
학습 결과 :  0.774621434983584
테스트 결과 :  0.8038651022229766
===================================================

In [170]:
from sklearn.pipeline import Pipeline

pipe = Pipeline([("scaler", StandardScaler()), ("model", SVR(kernel="linear"))])
params = [
    {
        "model__gamma":["scale", "auto"],
        "model__C":[10.0, 1.0, 0.1, 0.01, 0.001],
        "model__epsilon":[10.0, 1.0, 0.1, 0.01, 0.001]
    }
]

gs = GridSearchCV(
    estimator=pipe,
    param_grid=params,
    n_jobs=multiprocessing.cpu_count(),
    cv=5,
    verbose=True
)
gs.fit(X_train_std, y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('model', SVR(kernel='linear'))]),
             n_jobs=2,
             param_grid=[{'model__C': [10.0, 1.0, 0.1, 0.01, 0.001],
                          'model__epsilon': [10.0, 1.0, 0.1, 0.01, 0.001],
                          'model__gamma': ['scale', 'auto']}],
             verbose=True)

In [171]:
# gs로 best 값 찾기

print(gs.best_params_)
print(gs.best_estimator_)
print(gs.best_score_)

{'model__C': 10.0, 'model__epsilon': 10.0, 'model__gamma': 'scale'}
Pipeline(steps=[('scaler', StandardScaler()),
                ('model', SVR(C=10.0, epsilon=10.0, kernel='linear'))])
0.7477455604742925

In [172]:
# best 값 적용
model = SVR(kernel="linear", C=10.0, gamma="scale", epsilon=10.0)
model.fit(X_train_std, y_train)

print("학습 결과 : ", model.score(X_train_std, y_train))
print("테스트 결과 : ", model.score(X_test_std, y_test))

학습 결과 :  0.7661171825145996
테스트 결과 :  0.8043788756645747

## Gradient Boosting Model

- XGBoostRegressor(overfitting)
- LightGBMRegressor(overfitting)

### XGBoostRegressor - train: 99.76%, test: 83.62%, testscore_mean: 76.23%

In [173]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=0)

xgbr = XGBRegressor(n_estimators=300, learning_rate=0.08, max_depth=6, objective="reg:squarederror")
xgbr.fit(X_train, y_train)

print("훈련 정확도 : ", xgbr.score(X_train, y_train))
print("테스트 정확도 : ", xgbr.score(X_test, y_test))

# Overfitting, but test accuracy is pretty good

훈련 정확도 :  0.9959286403447919
테스트 정확도 :  0.8372996601627253

In [174]:
cross_val = cross_validate(estimator=xgbr, X=X, y=y, cv=15)

print("테스트 정확도 평균 : ", cross_val["test_score"].mean())

테스트 정확도 평균 :  0.7325635293008247

### LightGBM Regressor - train: 96.09%, test: 82.58%, testscore_mean: 75.84%

In [175]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.25, random_state=0)

lgbr = LGBMRegressor(n_estimator=100)
lgbr.fit(X_train, y_train, early_stopping_rounds=50, 
         eval_metric="logloss", eval_set=[(X_test, y_test)], verbose=True)

print("훈련 정확도 : ", lgbr.score(X_train, y_train))
print("테스트 정확도 : ", lgbr.score(X_test, y_test))

cross_val = cross_validate(estimator=lgbr, X=X, y=y, cv=15)
print("테스트 정확도 평균 : ", cross_val["test_score"].mean())

C:\Users\tagos71\anaconda3\lib\site-packages\lightgbm\sklearn.py:726: UserWarning: 'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. Pass 'early_stopping()' callback via 'callbacks' argument instead.
  _log_warning("'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. "
C:\Users\tagos71\anaconda3\lib\site-packages\lightgbm\sklearn.py:736: UserWarning: 'verbose' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose' argument is deprecated and will be removed in a future release of LightGBM. "

[LightGBM] [Warning] Unknown parameter: n_estimator
[1]	valid_0's l2: 39044.8
[2]	valid_0's l2: 34394.5
[3]	valid_0's l2: 30378.8
[4]	valid_0's l2: 27079.5
[5]	valid_0's l2: 24479.4
[6]	valid_0's l2: 22207.8
[7]	valid_0's l2: 20379.5
[8]	valid_0's l2: 18868.6
[9]	valid_0's l2: 17499.7
[10]	valid_0's l2: 16476.5
[11]	valid_0's l2: 15541.1
[12]	valid_0's l2: 14778.8
[13]	valid_0's l2: 14196.2
[14]	valid_0's l2: 13276.6
[15]	valid_0's l2: 12559.6
[16]	valid_0's l2: 11958.7
[17]	valid_0's l2: 11519.9
[18]	valid_0's l2: 11091.6
[19]	valid_0's l2: 10764.2
[20]	valid_0's l2: 10562.1
[21]	valid_0's l2: 10302.7
[22]	valid_0's l2: 10054.5
[23]	valid_0's l2: 9818.98
[24]	valid_0's l2: 9664.01
[25]	valid_0's l2: 9511.79
[26]	valid_0's l2: 9414.57
[27]	valid_0's l2: 9295.23
[28]	valid_0's l2: 9233.96
[29]	valid_0's l2: 9123.51
[30]	valid_0's l2: 9070.41
[31]	valid_0's l2: 9045.73
[32]	valid_0's l2: 8981.7
[33]	valid_0's l2: 8894.03
[34]	valid_0's l2: 8814.42
[35]	valid_0's l2: 8735.47
[36]	valid_0's l2: 8668.73
[37]	valid_0's l2: 8617.88
[38]	valid_0's l2: 8532.51
[39]	valid_0's l2: 8433.4
[40]	valid_0's l2: 8390.86
[41]	valid_0's l2: 8328.87
[42]	valid_0's l2: 8315.94
[43]	valid_0's l2: 8285.73
[44]	valid_0's l2: 8210.84
[45]	valid_0's l2: 8198.37
[46]	valid_0's l2: 8211.07
[47]	valid_0's l2: 8201.86
[48]	valid_0's l2: 8195.05
[49]	valid_0's l2: 8139.69
[50]	valid_0's l2: 8093.95
[51]	valid_0's l2: 8076.3
[52]	valid_0's l2: 8068.95
[53]	valid_0's l2: 8061.74
[54]	valid_0's l2: 8029.66
[55]	valid_0's l2: 8028.79
[56]	valid_0's l2: 7996.3
[57]	valid_0's l2: 8005.64
[58]	valid_0's l2: 7997.18
[59]	valid_0's l2: 7996.83
[60]	valid_0's l2: 7980.24
[61]	valid_0's l2: 7982.21
[62]	valid_0's l2: 8001.68
[63]	valid_0's l2: 7957.7
[64]	valid_0's l2: 7959.59
[65]	valid_0's l2: 7948.15
[66]	valid_0's l2: 7929.19
[67]	valid_0's l2: 7903.81
[68]	valid_0's l2: 7884.03
[69]	valid_0's l2: 7861.25
[70]	valid_0's l2: 7843.57
[71]	valid_0's l2: 7863.46
[72]	valid_0's l2: 7873.82
[73]	valid_0's l2: 7871.94
[74]	valid_0's l2: 7867.09
[75]	valid_0's l2: 7859
[76]	valid_0's l2: 7858.95
[77]	valid_0's l2: 7864.07
[78]	valid_0's l2: 7857.18
[79]	valid_0's l2: 7849.74
[80]	valid_0's l2: 7823.23
[81]	valid_0's l2: 7807.36
[82]	valid_0's l2: 7838.44
[83]	valid_0's l2: 7831.58
[84]	valid_0's l2: 7836.89
[85]	valid_0's l2: 7859.9
[86]	valid_0's l2: 7862.54
[87]	valid_0's l2: 7847.37
[88]	valid_0's l2: 7861.4
[89]	valid_0's l2: 7848.58
[90]	valid_0's l2: 7866.6
[91]	valid_0's l2: 7857.53
[92]	valid_0's l2: 7853.39
[93]	valid_0's l2: 7842.11
[94]	valid_0's l2: 7862.81
[95]	valid_0's l2: 7868.14
[96]	valid_0's l2: 7891.52
[97]	valid_0's l2: 7891.15
[98]	valid_0's l2: 7900.14
[99]	valid_0's l2: 7902.73
[100]	valid_0's l2: 7909.31
훈련 정확도 :  0.9640547997011811
테스트 정확도 :  0.8247515100167406
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
테스트 정확도 평균 :  0.7364497966288425

# Test data

In [176]:
ln_test = pd.read_csv("../byun/data/lunch_test_encoding.csv", encoding="utf-8")
ln_test

,datetime,year,month,date,worker_number,real_number,vacation_number,biztrip_number,overtime_number,telecom_number,...,season_winter,weekdays_friday,weekdays_monday,weekdays_thursday,weekdays_tuesday,weekdays_wednesday,vacation_N,vacation_Y,new_lunch_N,new_lunch_Y
0,2021-01-27,2021,1,27,2983,2355.0,88,182,5,358.0,...,1,0,0,0,0,1,1,0,1,0
1,2021-01-28,2021,1,28,2983,2319.0,104,212,409,348.0,...,1,0,0,1,0,0,1,0,1,0
2,2021-01-29,2021,1,29,2983,2170.0,270,249,0,294.0,...,1,1,0,0,0,0,1,0,1,0
3,2021-02-01,2021,2,1,2924,2340.0,108,154,538,322.0,...,1,0,1,0,0,0,1,0,1,0
4,2021-02-02,2021,2,2,2924,2362.0,62,186,455,314.0,...,1,0,0,0,1,0,1,0,1,0
5,2021-02-03,2021,2,3,2924,2380.0,59,199,5,286.0,...,1,0,0,0,0,1,1,0,1,0
6,2021-02-04,2021,2,4,2924,2364.0,61,211,476,288.0,...,1,0,0,1,0,0,1,0,1,0
7,2021-02-05,2021,2,5,2924,2247.0,169,252,0,256.0,...,1,1,0,0,0,0,1,0,1,0
8,2021-02-08,2021,2,8,2924,2333.0,88,174,690,329.0,...,1,0,1,0,0,0,1,0,1,0
9,2021-02-09,2021,2,9,2924,2318.0,94,183,542,329.0,...,1,0,0,0,1,0,1,0,1,0
10,2021-02-10,2021,2,10,2924,2068.0,489,134,0,233.0,...,1,0,0,0,0,1,0,1,1,0
11,2021-02-15,2021,2,15,2924,2260.0,178,131,795,355.0,...,1,0,1,0,0,0,1,0,1,0
12,2021-02-16,2021,2,16,2924,2266.0,70,175,815,413.0,...,1,0,0,0,1,0,1,0,1,0
13,2021-02-17,2021,2,17,2924,2287.0,77,181,3,379.0,...,1,0,0,0,0,1,1,0,1,0
14,2021-02-18,2021,2,18,2924,2256.0,83,247,594,338.0,...,1,0,0,1,0,0,1,0,1,0
15,2021-02-19,2021,2,19,2924,2200.0,176,268,1,280.0,...,1,1,0,0,0,0,1,0,1,0
16,2021-02-22,2021,2,22,2924,2375.0,105,197,814,247.0,...,1,0,1,0,0,0,1,0,1,0
17,2021-02-23,2021,2,23,2924,2416.0,75,200,783,233.0,...,1,0,0,0,1,0,1,0,1,0
18,2021-02-24,2021,2,24,2924,2378.0,77,235,3,234.0,...,1,0,0,0,0,1,1,0,1,0
19,2021-02-25,2021,2,25,2924,2346.0,91,252,585,235.0,...,1,0,0,1,0,0,1,0,1,0
20,2021-02-26,2021,2,26,2924,2205.0,261,279,1,179.0,...,1,1,0,0,0,0,0,1,1,0
21,2021-03-02,2021,3,2,2975,2422.0,139,166,781,248.0,...,0,0,0,0,1,0,1,0,1,0
22,2021-03-03,2021,3,3,2975,2438.0,50,195,1,292.0,...,0,0,0,0,0,1,1,0,1,0
23,2021-03-04,2021,3,4,2975,2404.0,72,236,746,263.0,...,0,0,0,1,0,0,1,0,1,0
24,2021-03-05,2021,3,5,2975,2334.0,158,257,2,226.0,...,0,1,0,0,0,0,1,0,1,0
25,2021-03-08,2021,3,8,2975,2444.0,97,170,939,264.0,...,0,0,1,0,0,0,1,0,0,1
26,2021-03-09,2021,3,9,2975,2447.0,76,170,1003,282.0,...,0,0,0,0,1,0,1,0,1,0
27,2021-03-10,2021,3,10,2975,2448.0,71,185,1,271.0,...,0,0,0,0,0,1,1,0,1,0
28,2021-03-11,2021,3,11,2975,2398.0,93,223,609,261.0,...,0,0,0,1,0,0,1,0,1,0
29,2021-03-12,2021,3,12,2975,2243.0,241,240,0,251.0,...,0,1,0,0,0,0,1,0,1,0
30,2021-03-15,2021,3,15,2975,2387.0,126,148,864,314.0,...,0,0,1,0,0,0,1,0,1,0
31,2021-03-16,2021,3,16,2975,2324.0,74,176,658,401.0,...,0,0,0,0,1,0,1,0,1,0
32,2021-03-17,2021,3,17,2975,2322.0,90,192,4,371.0,...,0,0,0,0,0,1,1,0,1,0
33,2021-03-18,2021,3,18,2975,2287.0,106,231,520,351.0,...,0,0,0,1,0,0,1,0,1,0
34,2021-03-19,2021,3,19,2975,2201.0,253,255,0,266.0,...,0,1,0,0,0,0,1,0,0,1
35,2021-03-22,2021,3,22,2975,2326.0,133,166,707,350.0,...,0,0,1,0,0,0,1,0,1,0
36,2021-03-23,2021,3,23,2975,2339.0,82,205,688,349.0,...,0,0,0,0,1,0,1,0,1,0
37,2021-03-24,2021,3,24,2975,2340.0,87,234,0,314.0,...,0,0,0,0,0,1,1,0,1,0
38,2021-03-25,2021,3,25,2975,2300.0,118,260,441,297.0,...,0,0,0,1,0,0,1,0,1,0
39,2021-03-26,2021,3,26,2975,2169.0,311,266,0,229.0,...,0,1,0,0,0,0,1,0,1,0
40,2021-03-29,2021,3,29,2975,2358.0,121,178,660,318.0,...,0,0,1,0,0,0,1,0,1,0
41,2021-03-30,2021,3,30,2975,2381.0,83,198,625,313.0,...,0,0,0,0,1,0,1,0,1,0
42,2021-03-31,2021,3,31,2975,2355.0,86,217,0,317.0,...,0,0,0,0,0,1,1,0,1,0
43,2021-04-01,2021,4,1,2973,2326.0,88,256,394,303.0,...,0,0,0,1,0,0,1,0,1,0
44,2021-04-02,2021,4,2,2973,2202.0,275,272,0,224.0,...,0,1,0,0,0,0,1,0,1,0
45,2021-04-05,2021,4,5,2973,2343.0,125,174,704,331.0,...,0,0,1,0,0,0,1,0,1,0
46,2021-04-06,2021,4,6,2973,2363.0,76,170,636,364.0,...,0,0,0,0,1,0,1,0,1,0
47,2021-04-07,2021,4,7,2973,2329.0,96,214,1,334.0,...,0,0,0,0,0,1,1,0,1,0
48,2021-04-08,2021,4,8,2973,2306.0,105,238,509,324.0,...,0,0,0,1,0,0,1,0,0,1
49,2021-04-09,2021,4,9,2973,2217.0,259,268,0,229.0,...,0,1,0,0,0,0,1,0,1,0

In [177]:
summer = []
fall = []

for i in range(len(ln_test)):
    summer.append(0)
    fall.append(0)
    
ln_test['season_summer'] = summer
ln_test['season_fall'] = fall

ln_test

,datetime,year,month,date,worker_number,real_number,vacation_number,biztrip_number,overtime_number,telecom_number,...,weekdays_monday,weekdays_thursday,weekdays_tuesday,weekdays_wednesday,vacation_N,vacation_Y,new_lunch_N,new_lunch_Y,season_summer,season_fall
0,2021-01-27,2021,1,27,2983,2355.0,88,182,5,358.0,...,0,0,0,1,1,0,1,0,0,0
1,2021-01-28,2021,1,28,2983,2319.0,104,212,409,348.0,...,0,1,0,0,1,0,1,0,0,0
2,2021-01-29,2021,1,29,2983,2170.0,270,249,0,294.0,...,0,0,0,0,1,0,1,0,0,0
3,2021-02-01,2021,2,1,2924,2340.0,108,154,538,322.0,...,1,0,0,0,1,0,1,0,0,0
4,2021-02-02,2021,2,2,2924,2362.0,62,186,455,314.0,...,0,0,1,0,1,0,1,0,0,0
5,2021-02-03,2021,2,3,2924,2380.0,59,199,5,286.0,...,0,0,0,1,1,0,1,0,0,0
6,2021-02-04,2021,2,4,2924,2364.0,61,211,476,288.0,...,0,1,0,0,1,0,1,0,0,0
7,2021-02-05,2021,2,5,2924,2247.0,169,252,0,256.0,...,0,0,0,0,1,0,1,0,0,0
8,2021-02-08,2021,2,8,2924,2333.0,88,174,690,329.0,...,1,0,0,0,1,0,1,0,0,0
9,2021-02-09,2021,2,9,2924,2318.0,94,183,542,329.0,...,0,0,1,0,1,0,1,0,0,0
10,2021-02-10,2021,2,10,2924,2068.0,489,134,0,233.0,...,0,0,0,1,0,1,1,0,0,0
11,2021-02-15,2021,2,15,2924,2260.0,178,131,795,355.0,...,1,0,0,0,1,0,1,0,0,0
12,2021-02-16,2021,2,16,2924,2266.0,70,175,815,413.0,...,0,0,1,0,1,0,1,0,0,0
13,2021-02-17,2021,2,17,2924,2287.0,77,181,3,379.0,...,0,0,0,1,1,0,1,0,0,0
14,2021-02-18,2021,2,18,2924,2256.0,83,247,594,338.0,...,0,1,0,0,1,0,1,0,0,0
15,2021-02-19,2021,2,19,2924,2200.0,176,268,1,280.0,...,0,0,0,0,1,0,1,0,0,0
16,2021-02-22,2021,2,22,2924,2375.0,105,197,814,247.0,...,1,0,0,0,1,0,1,0,0,0
17,2021-02-23,2021,2,23,2924,2416.0,75,200,783,233.0,...,0,0,1,0,1,0,1,0,0,0
18,2021-02-24,2021,2,24,2924,2378.0,77,235,3,234.0,...,0,0,0,1,1,0,1,0,0,0
19,2021-02-25,2021,2,25,2924,2346.0,91,252,585,235.0,...,0,1,0,0,1,0,1,0,0,0
20,2021-02-26,2021,2,26,2924,2205.0,261,279,1,179.0,...,0,0,0,0,0,1,1,0,0,0
21,2021-03-02,2021,3,2,2975,2422.0,139,166,781,248.0,...,0,0,1,0,1,0,1,0,0,0
22,2021-03-03,2021,3,3,2975,2438.0,50,195,1,292.0,...,0,0,0,1,1,0,1,0,0,0
23,2021-03-04,2021,3,4,2975,2404.0,72,236,746,263.0,...,0,1,0,0,1,0,1,0,0,0
24,2021-03-05,2021,3,5,2975,2334.0,158,257,2,226.0,...,0,0,0,0,1,0,1,0,0,0
25,2021-03-08,2021,3,8,2975,2444.0,97,170,939,264.0,...,1,0,0,0,1,0,0,1,0,0
26,2021-03-09,2021,3,9,2975,2447.0,76,170,1003,282.0,...,0,0,1,0,1,0,1,0,0,0
27,2021-03-10,2021,3,10,2975,2448.0,71,185,1,271.0,...,0,0,0,1,1,0,1,0,0,0
28,2021-03-11,2021,3,11,2975,2398.0,93,223,609,261.0,...,0,1,0,0,1,0,1,0,0,0
29,2021-03-12,2021,3,12,2975,2243.0,241,240,0,251.0,...,0,0,0,0,1,0,1,0,0,0
30,2021-03-15,2021,3,15,2975,2387.0,126,148,864,314.0,...,1,0,0,0,1,0,1,0,0,0
31,2021-03-16,2021,3,16,2975,2324.0,74,176,658,401.0,...,0,0,1,0,1,0,1,0,0,0
32,2021-03-17,2021,3,17,2975,2322.0,90,192,4,371.0,...,0,0,0,1,1,0,1,0,0,0
33,2021-03-18,2021,3,18,2975,2287.0,106,231,520,351.0,...,0,1,0,0,1,0,1,0,0,0
34,2021-03-19,2021,3,19,2975,2201.0,253,255,0,266.0,...,0,0,0,0,1,0,0,1,0,0
35,2021-03-22,2021,3,22,2975,2326.0,133,166,707,350.0,...,1,0,0,0,1,0,1,0,0,0
36,2021-03-23,2021,3,23,2975,2339.0,82,205,688,349.0,...,0,0,1,0,1,0,1,0,0,0
37,2021-03-24,2021,3,24,2975,2340.0,87,234,0,314.0,...,0,0,0,1,1,0,1,0,0,0
38,2021-03-25,2021,3,25,2975,2300.0,118,260,441,297.0,...,0,1,0,0,1,0,1,0,0,0
39,2021-03-26,2021,3,26,2975,2169.0,311,266,0,229.0,...,0,0,0,0,1,0,1,0,0,0
40,2021-03-29,2021,3,29,2975,2358.0,121,178,660,318.0,...,1,0,0,0,1,0,1,0,0,0
41,2021-03-30,2021,3,30,2975,2381.0,83,198,625,313.0,...,0,0,1,0,1,0,1,0,0,0
42,2021-03-31,2021,3,31,2975,2355.0,86,217,0,317.0,...,0,0,0,1,1,0,1,0,0,0
43,2021-04-01,2021,4,1,2973,2326.0,88,256,394,303.0,...,0,1,0,0,1,0,1,0,0,0
44,2021-04-02,2021,4,2,2973,2202.0,275,272,0,224.0,...,0,0,0,0,1,0,1,0,0,0
45,2021-04-05,2021,4,5,2973,2343.0,125,174,704,331.0,...,1,0,0,0,1,0,1,0,0,0
46,2021-04-06,2021,4,6,2973,2363.0,76,170,636,364.0,...,0,0,1,0,1,0,1,0,0,0
47,2021-04-07,2021,4,7,2973,2329.0,96,214,1,334.0,...,0,0,0,1,1,0,1,0,0,0
48,2021-04-08,2021,4,8,2973,2306.0,105,238,509,324.0,...,0,1,0,0,1,0,0,1,0,0
49,2021-04-09,2021,4,9,2973,2217.0,259,268,0,229.0,...,0,0,0,0,1,0,1,0,0,0

In [178]:
columns = ['datetime', 'year', 'month', 'date', 'worker_number', 'real_number',
       'vacation_number', 'biztrip_number', 'overtime_number',
       'telecom_number', 'temperature', 'rain', 'wind', 'humidity',
       'discomfort_index', 'perceived_temperature', 'lunch_rice',
       'season_fall','season_spring', 'season_summer', 'season_winter', 'weekdays_friday', 'weekdays_monday',
       'weekdays_thursday', 'weekdays_tuesday', 'weekdays_wednesday',
       'vacation_N', 'vacation_Y', 'new_lunch_N', 'new_lunch_Y']

ln_test.coulmns = columns

<ipython-input-178-695c2266ae23>:9: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  ln_test.coulmns = columns

In [179]:
ln_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   datetime               50 non-null     object
 1   year                   50 non-null     int64
 2   month                  50 non-null     int64
 3   date                   50 non-null     int64
 4   worker_number          50 non-null     int64
 5   real_number            50 non-null     float64
 6   vacation_number        50 non-null     int64
 7   biztrip_number         50 non-null     int64
 8   overtime_number        50 non-null     int64
 9   telecom_number         50 non-null     float64
 10  temperature            50 non-null     float64
 11  rain                   50 non-null     float64
 12  wind                   50 non-null     float64
 13  humidity               50 non-null     float64
 14  discomfort_index       50 non-null     float64
 15  perceived_temperature  50 non-null     float64
 16  lunch_rice             50 non-null     int64
 17  season_spring          50 non-null     int64
 18  season_winter          50 non-null     int64
 19  weekdays_friday        50 non-null     int64
 20  weekdays_monday        50 non-null     int64
 21  weekdays_thursday      50 non-null     int64
 22  weekdays_tuesday       50 non-null     int64
 23  weekdays_wednesday     50 non-null     int64
 24  vacation_N             50 non-null     int64
 25  vacation_Y             50 non-null     int64
 26  new_lunch_N            50 non-null     int64
 27  new_lunch_Y            50 non-null     int64
 28  season_summer          50 non-null     int64
 29  season_fall            50 non-null     int64
dtypes: float64(8), int64(21), object(1)
memory usage: 11.8+ KB

In [180]:
X_Test= ln_test.drop(columns=["datetime", "year", "month", "date"], axis=1)
X_Test.shape
X_Test

,worker_number,real_number,vacation_number,biztrip_number,overtime_number,telecom_number,temperature,rain,wind,humidity,...,weekdays_monday,weekdays_thursday,weekdays_tuesday,weekdays_wednesday,vacation_N,vacation_Y,new_lunch_N,new_lunch_Y,season_summer,season_fall
0,2983,2355.0,88,182,5,358.0,4.1,0.0,0.9,61.5,...,0,0,0,1,1,0,1,0,0,0
1,2983,2319.0,104,212,409,348.0,1.4,0.0,2.3,58.1,...,0,1,0,0,1,0,1,0,0,0
2,2983,2170.0,270,249,0,294.0,-2.3,0.0,2.1,39.4,...,0,0,0,0,1,0,1,0,0,0
3,2924,2340.0,108,154,538,322.0,7.5,16.0,1.0,84.5,...,1,0,0,0,1,0,1,0,0,0
4,2924,2362.0,62,186,455,314.0,0.4,0.0,2.3,36.0,...,0,0,1,0,1,0,1,0,0,0
5,2924,2380.0,59,199,5,286.0,-1.6,0.0,0.8,56.3,...,0,0,0,1,1,0,1,0,0,0
6,2924,2364.0,61,211,476,288.0,2.4,0.0,1.0,50.3,...,0,1,0,0,1,0,1,0,0,0
7,2924,2247.0,169,252,0,256.0,1.2,0.0,0.7,52.5,...,0,0,0,0,1,0,1,0,0,0
8,2924,2333.0,88,174,690,329.0,2.2,0.0,2.1,28.6,...,1,0,0,0,1,0,1,0,0,0
9,2924,2318.0,94,183,542,329.0,-0.2,0.0,0.7,46.6,...,0,0,1,0,1,0,1,0,0,0
10,2924,2068.0,489,134,0,233.0,1.9,0.0,0.5,57.9,...,0,0,0,1,0,1,1,0,0,0
11,2924,2260.0,178,131,795,355.0,6.0,0.0,1.3,66.1,...,1,0,0,0,1,0,1,0,0,0
12,2924,2266.0,70,175,815,413.0,0.7,0.0,1.9,57.5,...,0,0,1,0,1,0,1,0,0,0
13,2924,2287.0,77,181,3,379.0,-3.0,0.0,3.4,40.4,...,0,0,0,1,1,0,1,0,0,0
14,2924,2256.0,83,247,594,338.0,-2.5,0.0,1.8,47.1,...,0,1,0,0,1,0,1,0,0,0
15,2924,2200.0,176,268,1,280.0,3.1,0.0,1.7,57.6,...,0,0,0,0,1,0,1,0,0,0
16,2924,2375.0,105,197,814,247.0,14.3,0.0,1.8,55.3,...,1,0,0,0,1,0,1,0,0,0
17,2924,2416.0,75,200,783,233.0,6.9,0.0,1.1,29.5,...,0,0,1,0,1,0,1,0,0,0
18,2924,2378.0,77,235,3,234.0,3.6,0.0,0.5,40.5,...,0,0,0,1,1,0,1,0,0,0
19,2924,2346.0,91,252,585,235.0,4.3,2.6,0.6,77.5,...,0,1,0,0,1,0,1,0,0,0
20,2924,2205.0,261,279,1,179.0,8.7,2.4,1.5,67.9,...,0,0,0,0,0,1,1,0,0,0
21,2975,2422.0,139,166,781,248.0,5.2,1.9,1.7,76.3,...,0,0,1,0,1,0,1,0,0,0
22,2975,2438.0,50,195,1,292.0,3.8,0.0,0.7,71.6,...,0,0,0,1,1,0,1,0,0,0
23,2975,2404.0,72,236,746,263.0,5.2,7.5,0.5,90.0,...,0,1,0,0,1,0,1,0,0,0
24,2975,2334.0,158,257,2,226.0,10.6,0.0,0.8,77.5,...,0,0,0,0,1,0,1,0,0,0
25,2975,2444.0,97,170,939,264.0,7.3,0.0,0.8,71.5,...,1,0,0,0,1,0,0,1,0,0
26,2975,2447.0,76,170,1003,282.0,9.2,0.0,0.7,70.0,...,0,0,1,0,1,0,1,0,0,0
27,2975,2448.0,71,185,1,271.0,8.4,0.0,0.9,63.8,...,0,0,0,1,1,0,1,0,0,0
28,2975,2398.0,93,223,609,261.0,9.4,0.7,0.7,71.1,...,0,1,0,0,1,0,1,0,0,0
29,2975,2243.0,241,240,0,251.0,9.0,25.2,1.4,90.1,...,0,0,0,0,1,0,1,0,0,0
30,2975,2387.0,126,148,864,314.0,10.5,0.3,0.8,77.4,...,1,0,0,0,1,0,1,0,0,0
31,2975,2324.0,74,176,658,401.0,13.9,1.8,0.9,64.5,...,0,0,1,0,1,0,1,0,0,0
32,2975,2322.0,90,192,4,371.0,9.2,0.0,0.7,61.0,...,0,0,0,1,1,0,1,0,0,0
33,2975,2287.0,106,231,520,351.0,10.8,0.0,1.0,72.6,...,0,1,0,0,1,0,1,0,0,0
34,2975,2201.0,253,255,0,266.0,12.3,0.0,1.7,62.6,...,0,0,0,0,1,0,0,1,0,0
35,2975,2326.0,133,166,707,350.0,7.3,0.0,2.4,40.6,...,1,0,0,0,1,0,1,0,0,0
36,2975,2339.0,82,205,688,349.0,9.1,0.0,1.3,55.8,...,0,0,1,0,1,0,1,0,0,0
37,2975,2340.0,87,234,0,314.0,9.9,0.0,1.0,67.4,...,0,0,0,1,1,0,1,0,0,0
38,2975,2300.0,118,260,441,297.0,12.1,0.0,0.8,64.3,...,0,1,0,0,1,0,1,0,0,0
39,2975,2169.0,311,266,0,229.0,12.4,0.0,0.8,58.4,...,0,0,0,0,1,0,1,0,0,0
40,2975,2358.0,121,178,660,318.0,13.6,0.0,0.8,59.4,...,1,0,0,0,1,0,1,0,0,0
41,2975,2381.0,83,198,625,313.0,12.2,0.0,0.7,52.3,...,0,0,1,0,1,0,1,0,0,0
42,2975,2355.0,86,217,0,317.0,12.1,0.0,0.7,65.0,...,0,0,0,1,1,0,1,0,0,0
43,2973,2326.0,88,256,394,303.0,14.0,0.0,1.8,53.3,...,0,1,0,0,1,0,1,0,0,0
44,2973,2202.0,275,272,0,224.0,17.2,0.0,1.7,56.9,...,0,0,0,0,1,0,1,0,0,0
45,2973,2343.0,125,174,704,331.0,10.5,0.0,1.3,58.9,...,1,0,0,0,1,0,1,0,0,0
46,2973,2363.0,76,170,636,364.0,11.3,0.0,0.7,60.0,...,0,0,1,0,1,0,1,0,0,0
47,2973,2329.0,96,214,1,334.0,13.3,0.0,1.0,58.6,...,0,0,0,1,1,0,1,0,0,0
48,2973,2306.0,105,238,509,324.0,12.9,0.0,0.8,64.1,...,0,1,0,0,1,0,0,1,0,0
49,2973,2217.0,259,268,0,229.0,10.5,0.0,1.5,66.0,...,0,0,0,0,1,0,1,0,0,0

In [181]:
model = LinearRegression()
model.fit(X, y)

preds = model.predict(X_Test)
print(preds)

[ 803.95503564  848.49623221  658.63786694 1078.01337158 1156.58510861
  796.62050347  887.99655564  700.71225456 1064.30861834 1138.72214905
  777.20801456 1118.56682548 1242.36418047  838.03345066  837.20816518
  678.77769831 1048.6011649  1185.78049317  711.17306294  823.37135359
  722.58547009 1262.12190731  838.00967122  930.15330561  744.13443009
 1090.44996336 1322.51617441  854.07114939  910.62201595  762.85785123
 1159.22826139 1226.36976245  814.44933005  859.89847386  631.96342167
 1079.73977421 1172.10910315  748.02509604  779.93803524  634.38914086
 1051.26018522 1169.25547233  775.82664606  793.94851485  646.38439184
 1068.93695354 1225.93854761  774.14474398  782.37602046  661.20316323]

In [182]:
submission = pd.DataFrame({"datetime":ln_test["datetime"], "lunch_number":preds})
submission

      datetime  lunch_number
0   2021-01-27    803.955036
1   2021-01-28    848.496232
2   2021-01-29    658.637867
3   2021-02-01   1078.013372
4   2021-02-02   1156.585109
5   2021-02-03    796.620503
6   2021-02-04    887.996556
7   2021-02-05    700.712255
8   2021-02-08   1064.308618
9   2021-02-09   1138.722149
10  2021-02-10    777.208015
11  2021-02-15   1118.566825
12  2021-02-16   1242.364180
13  2021-02-17    838.033451
14  2021-02-18    837.208165
15  2021-02-19    678.777698
16  2021-02-22   1048.601165
17  2021-02-23   1185.780493
18  2021-02-24    711.173063
19  2021-02-25    823.371354
20  2021-02-26    722.585470
21  2021-03-02   1262.121907
22  2021-03-03    838.009671
23  2021-03-04    930.153306
24  2021-03-05    744.134430
25  2021-03-08   1090.449963
26  2021-03-09   1322.516174
27  2021-03-10    854.071149
28  2021-03-11    910.622016
29  2021-03-12    762.857851
30  2021-03-15   1159.228261
31  2021-03-16   1226.369762
32  2021-03-17    814.449330
33  2021-03-18    859.898474
34  2021-03-19    631.963422
35  2021-03-22   1079.739774
36  2021-03-23   1172.109103
37  2021-03-24    748.025096
38  2021-03-25    779.938035
39  2021-03-26    634.389141
40  2021-03-29   1051.260185
41  2021-03-30   1169.255472
42  2021-03-31    775.826646
43  2021-04-01    793.948515
44  2021-04-02    646.384392
45  2021-04-05   1068.936954
46  2021-04-06   1225.938548
47  2021-04-07    774.144744
48  2021-04-08    782.376020
49  2021-04-09    661.203163

# 구내식당 석식 인원 예측 모델

In [4]:
dn_train = pd.read_csv("../byun/data/dinner_df_encoding.csv", encoding="utf-8")
dn_train

,datetime,year,month,date,worker_number,real_number,vacation_number,biztrip_number,overtime_number,telecom_number,...,season_winter,weekdays_friday,weekdays_monday,weekdays_thursday,weekdays_tuesday,weekdays_wednesday,vacation_N,vacation_Y,new_dinner_N,new_dinner_Y
0,2016-02-01,2016,2,1,2601,2401,50,150,238,0,...,1,0,1,0,0,0,1,0,1,0
1,2016-02-02,2016,2,2,2601,2378,50,173,319,0,...,1,0,0,0,1,0,1,0,1,0
2,2016-02-03,2016,2,3,2601,2365,56,180,111,0,...,1,0,0,0,0,1,1,0,1,0
3,2016-02-04,2016,2,4,2601,2277,104,220,355,0,...,1,0,0,1,0,0,1,0,1,0
4,2016-02-05,2016,2,5,2601,2142,278,181,34,0,...,1,1,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1200,2021-01-20,2021,1,20,2983,2319,75,198,4,391,...,1,0,0,0,0,1,1,0,1,0
1201,2021-01-21,2021,1,21,2983,2309,92,231,462,351,...,1,0,0,1,0,0,1,0,1,0
1202,2021-01-22,2021,1,22,2983,2177,255,248,1,303,...,1,1,0,0,0,0,1,0,1,0
1203,2021-01-25,2021,1,25,2983,2396,107,153,616,327,...,1,0,1,0,0,0,1,0,1,0
1204,2021-01-26,2021,1,26,2983,2369,69,183,551,362,...,1,0,0,0,1,0,1,0,0,1

In [9]:
dn_train.isnull().sum()
dn_train = dn_train.dropna()

datetime                 0
year                     0
month                    0
date                     0
worker_number            0
real_number              0
vacation_number          0
biztrip_number           0
overtime_number          0
telecom_number           0
temperature              0
rain                     0
wind                     0
humidity                 0
discomfort_index         0
perceived_temperature    0
dinner_rice              0
dinner_number            0
season_fall              0
season_spring            0
season_summer            0
season_winter            0
weekdays_friday          0
weekdays_monday          0
weekdays_thursday        0
weekdays_tuesday         0
weekdays_wednesday       0
vacation_N               0
vacation_Y               0
new_dinner_N             0
new_dinner_Y             0
dtype: int64

## 선형회귀(일반) - train: 52.53%, test: 48.01%

In [127]:
X = dn_train.drop(columns=["datetime", "dinner_number"], axis=1)

y = dn_train["dinner_number"]

y = y.to_numpy()


lr = LinearRegression().fit(X, y)
print("훈련 점수 : ", lr.score(X, y))
print("========================================================")
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
lr = LinearRegression().fit(X_train, y_train)

print("훈련 점수 : ", lr.score(X_train, y_train))
print("테스트 점수 : ", lr.score(X_test, y_test))

훈련 점수 :  0.5249828965311587
========================================================
훈련 점수 :  0.5252706818889732
테스트 점수 :  0.4801202488360182

## 릿지회귀모델 - train: 53.11%, test: 50.38%

In [130]:

ridge = Ridge().fit(X_train, y_train) 

print("훈련 점수 : ", ridge.score(X_train, y_train))
print("테스트 점수 : ", ridge.score(X_test, y_test))
print("========================================================")

ridge10 = Ridge(alpha=100).fit(X_train, y_train) 

print("훈련 점수 : ", ridge10.score(X_train, y_train))
print("테스트 점수 : ", ridge10.score(X_test, y_test))

print("========================================================")
ridge01 = Ridge(alpha=0.000000001).fit(X_train, y_train) 

print("훈련 점수 : ", ridge01.score(X_train, y_train))
print("테스트 점수 : ", ridge01.score(X_test, y_test))

훈련 점수 :  0.5311031341997445
테스트 점수 :  0.5038654429839337
========================================================
훈련 점수 :  0.5215506664632992
테스트 점수 :  0.5000294643047009
========================================================
훈련 점수 :  0.5311097299673089
테스트 점수 :  0.5034655621849163

## 라쏘회귀모델 - train: 53.10%, test: 50.47%

In [131]:

lasso = Lasso().fit(X_train, y_train) #Lasso(alpha=1) 디폴트

print("훈련 점수 : ", lasso.score(X_train, y_train))
print("테스트 점수 : ", lasso.score(X_test, y_test)) 

print("사용한 특성의 수 : ", np.sum(lasso.coef_ != 0)) 
print("========================================================")
lasso001 = Lasso(alpha=0.01).fit(X_train, y_train)

print("훈련 점수 : ", lasso001.score(X_train, y_train))
print("테스트 점수 : ", lasso001.score(X_test, y_test))

print("사용한 특성의 수 : ", np.sum(lasso001.coef_ != 0))
print("========================================================")
lasso00001 = Lasso(alpha=0.000000001).fit(X_train, y_train)

print("훈련 점수 : ", lasso00001.score(X_train, y_train))
print("테스트 점수 : ", lasso00001.score(X_test, y_test)) 

print("사용한 특성의 수 : ", np.sum(lasso00001.coef_ != 0))

# Lasso: lower alpha makes greater score

훈련 점수 :  0.52748563774949
테스트 점수 :  0.49556220016851027
사용한 특성의 수 :  16
========================================================
훈련 점수 :  0.5309736286294525
테스트 점수 :  0.5047508824135023
사용한 특성의 수 :  25
========================================================
훈련 점수 :  0.530983084214575
테스트 점수 :  0.5046886765270251
사용한 특성의 수 :  27

C:\Users\tagos71\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 37772.5374730397, tolerance: 1899.8009273388775
  model = cd_fast.enet_coordinate_descent(
C:\Users\tagos71\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4273734.057619, tolerance: 1899.8009273388775
  model = cd_fast.enet_coordinate_descent(
C:\Users\tagos71\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 4455193.840111321, tolerance: 1899.8009273388775
  model = cd_fast.enet_coordinate_descent(

## SVR model - train: 47.37%, test: 48.92%

- Normal
- Kernel("linear" is best)
- StandardScaler // MinMaxScaler

In [132]:
model = SVR()  # default is rbf
model.fit(X_train, y_train)

print("rbf 학습 결과 : ", model.score(X_train, y_train))
print("rbf 테스트 결과 : ", model.score(X_test, y_test))
print('===================================================')
# Too bad

linear_svr = SVR(kernel="linear")
linear_svr.fit(X_train, y_train)

print("linear 학습 결과 : ", linear_svr.score(X_train, y_train))
print("linear 테스트 결과 : ", linear_svr.score(X_test, y_test))

print('===================================================')

linear_svr = SVR(kernel="linear", C=10, gamma='scale')
linear_svr.fit(X_train, y_train)

print("C=10 학습 결과 : ", linear_svr.score(X_train, y_train))
print("C=10 테스트 결과 : ", linear_svr.score(X_test, y_test))

print('===================================================')
### 정규화 해보자

scaler = MinMaxScaler()
X_train_mms = scaler.fit_transform(X_train)
X_test_mms = scaler.transform(X_test)

model = SVR(kernel='linear')
model.fit(X_train_mms, y_train)

print("minmax 학습 결과 : ", model.score(X_train_mms, y_train))
print("minmax 테스트 결과 : ", model.score(X_test_mms, y_test))

print('===================================================')
### 표준화 해보자

scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

model = SVR(kernel='linear')
model.fit(X_train_std, y_train)

print("std 학습 결과 : ", model.score(X_train_std, y_train))
print("std 테스트 결과 : ", model.score(X_test_std, y_test))
print('===================================================')
## 표준화만 했는데도 성능이 좋아짐

model = SVR(kernel='linear', C=10)
model.fit(X_train_std, y_train)

print("std 학습 결과 : ", model.score(X_train_std, y_train))
print("std 테스트 결과 : ", model.score(X_test_std, y_test))
print('===================================================')
model = SVR(kernel='linear', C=10, gamma='auto')
model.fit(X_train_std, y_train)

print("std 학습 결과 : ", model.score(X_train_std, y_train))
print("std 테스트 결과 : ", model.score(X_test_std, y_test))
print('===================================================')
# gamma=scale & gamma=auto are same score

rbf 학습 결과 :  0.010646474562626795
rbf 테스트 결과 :  0.016858563236203272
===================================================
linear 학습 결과 :  0.46862264208574655
linear 테스트 결과 :  0.4801582231467556
===================================================
C=10 학습 결과 :  0.4107284966793153
C=10 테스트 결과 :  0.4156136971305534
===================================================
minmax 학습 결과 :  0.30436378634899075
minmax 테스트 결과 :  0.3277430079338134
===================================================
std 학습 결과 :  0.4496245524967396
std 테스트 결과 :  0.4889316348352648
std 학습 결과 :  0.4676095195114729
std 테스트 결과 :  0.49049424946629216
===================================================
std 학습 결과 :  0.4676095195114729
std 테스트 결과 :  0.49049424946629216
===================================================

In [133]:
pipe = Pipeline([("scaler", StandardScaler()), ("model", SVR(kernel="linear"))])
params = [
    {
        "model__gamma":["scale", "auto"],
        "model__C":[10.0, 1.0, 0.1, 0.01, 0.001],
        "model__epsilon":[10.0, 1.0, 0.1, 0.01, 0.001]
    }
]

gs = GridSearchCV(
    estimator=pipe,
    param_grid=params,
    n_jobs=multiprocessing.cpu_count(),
    cv=5,
    verbose=True
)
gs.fit(X_train_std, y_train)

# gs로 best 값 찾기

print(gs.best_params_)
print(gs.best_estimator_)
print(gs.best_score_)

Fitting 5 folds for each of 50 candidates, totalling 250 fits
{'model__C': 10.0, 'model__epsilon': 10.0, 'model__gamma': 'scale'}
Pipeline(steps=[('scaler', StandardScaler()),
                ('model', SVR(C=10.0, epsilon=10.0, kernel='linear'))])
0.4513764264071106

In [134]:
# best 값 적용 (linear kernel, C=10, gamma=scale, epsilon=10)
model = SVR(kernel="linear", C=10.0, gamma="scale", epsilon=10.0)
model.fit(X_train_std, y_train)

print("학습 결과 : ", model.score(X_train_std, y_train))
print("테스트 결과 : ", model.score(X_test_std, y_test))

학습 결과 :  0.47365202201080825
테스트 결과 :  0.4892416502784851

## Gradient Boosting Model

- XGBoostRegressor(overfitting)
- LightGBMRegressor(overfitting)

### XGBoostRegressor - train: 99.75%, test: 59.65%, testscore_mean: 47.67%

In [136]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=0)

xgbr = XGBRegressor(n_estimators=300, learning_rate=0.08, max_depth=6, objective="reg:squarederror")
xgbr.fit(X_train, y_train)

print("훈련 정확도 : ", xgbr.score(X_train, y_train))
print("테스트 정확도 : ", xgbr.score(X_test, y_test))

# Overfitting, but test accuracy is pretty good

cross_val = cross_validate(estimator=xgbr, X=X, y=y, cv=15)

print("테스트 정확도 평균 : ", cross_val["test_score"].mean())

훈련 정확도 :  0.9975370548819197
테스트 정확도 :  0.5965483412762536
테스트 정확도 평균 :  0.476700659293617

### LightGBM Regressor - train: 86.45%, test: 64.45%, testscore_mean: 42.10%

In [140]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=0)

lgbr = LGBMRegressor(n_estimator=100)
lgbr.fit(X_train, y_train, early_stopping_rounds=50, 
         eval_metric="logloss", eval_set=[(X_test, y_test)], verbose=True)

print("훈련 정확도 : ", lgbr.score(X_train, y_train))
print("테스트 정확도 : ", lgbr.score(X_test, y_test))

cross_val = cross_validate(estimator=lgbr, X=X, y=y, cv=50)
print("테스트 정확도 평균 : ", cross_val["test_score"].mean())

C:\Users\tagos71\anaconda3\lib\site-packages\lightgbm\sklearn.py:726: UserWarning: 'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. Pass 'early_stopping()' callback via 'callbacks' argument instead.
  _log_warning("'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. "
C:\Users\tagos71\anaconda3\lib\site-packages\lightgbm\sklearn.py:736: UserWarning: 'verbose' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose' argument is deprecated and will be removed in a future release of LightGBM. "

[LightGBM] [Warning] Unknown parameter: n_estimator
[1]	valid_0's l2: 15767.3
[2]	valid_0's l2: 14153.1
[3]	valid_0's l2: 12808.4
[4]	valid_0's l2: 11709.4
[5]	valid_0's l2: 10919.7
[6]	valid_0's l2: 10169.9
[7]	valid_0's l2: 9634.86
[8]	valid_0's l2: 9108.44
[9]	valid_0's l2: 8726.46
[10]	valid_0's l2: 8372.79
[11]	valid_0's l2: 8053.49
[12]	valid_0's l2: 7737.02
[13]	valid_0's l2: 7581.52
[14]	valid_0's l2: 7447.18
[15]	valid_0's l2: 7338.17
[16]	valid_0's l2: 7250.65
[17]	valid_0's l2: 7164.39
[18]	valid_0's l2: 7070.14
[19]	valid_0's l2: 6992.86
[20]	valid_0's l2: 6925.49
[21]	valid_0's l2: 6814.47
[22]	valid_0's l2: 6781.16
[23]	valid_0's l2: 6762.36
[24]	valid_0's l2: 6674.79
[25]	valid_0's l2: 6592.34
[26]	valid_0's l2: 6544.76
[27]	valid_0's l2: 6542.26
[28]	valid_0's l2: 6504.61
[29]	valid_0's l2: 6476.07
[30]	valid_0's l2: 6458.16
[31]	valid_0's l2: 6405.99
[32]	valid_0's l2: 6375.29
[33]	valid_0's l2: 6399.97
[34]	valid_0's l2: 6449.66
[35]	valid_0's l2: 6462.74
[36]	valid_0's l2: 6521.71
[37]	valid_0's l2: 6553.13
[38]	valid_0's l2: 6557.42
[39]	valid_0's l2: 6592.46
[40]	valid_0's l2: 6624.7
[41]	valid_0's l2: 6624.56
[42]	valid_0's l2: 6656.8
[43]	valid_0's l2: 6685.58
[44]	valid_0's l2: 6664.07
[45]	valid_0's l2: 6701.56
[46]	valid_0's l2: 6712.78
[47]	valid_0's l2: 6704.5
[48]	valid_0's l2: 6721.65
[49]	valid_0's l2: 6743.72
[50]	valid_0's l2: 6765.2
[51]	valid_0's l2: 6760.99
[52]	valid_0's l2: 6777.85
[53]	valid_0's l2: 6816.47
[54]	valid_0's l2: 6842.84
[55]	valid_0's l2: 6846.8
[56]	valid_0's l2: 6860.42
[57]	valid_0's l2: 6887.44
[58]	valid_0's l2: 6867.37
[59]	valid_0's l2: 6842.34
[60]	valid_0's l2: 6841.55
[61]	valid_0's l2: 6837.33
[62]	valid_0's l2: 6828.89
[63]	valid_0's l2: 6813.63
[64]	valid_0's l2: 6817.86
[65]	valid_0's l2: 6819.92
[66]	valid_0's l2: 6826.3
[67]	valid_0's l2: 6852.02
[68]	valid_0's l2: 6855.51
[69]	valid_0's l2: 6840.94
[70]	valid_0's l2: 6845.01
[71]	valid_0's l2: 6856.02
[72]	valid_0's l2: 6850.82
[73]	valid_0's l2: 6866.81
[74]	valid_0's l2: 6874.13
[75]	valid_0's l2: 6878.37
[76]	valid_0's l2: 6877.54
[77]	valid_0's l2: 6882.17
[78]	valid_0's l2: 6887.03
[79]	valid_0's l2: 6903.98
[80]	valid_0's l2: 6896.63
[81]	valid_0's l2: 6887.95
[82]	valid_0's l2: 6903.47
훈련 정확도 :  0.8645438399379478
테스트 정확도 :  0.6445426365937541
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
[LightGBM] [Warning] Unknown parameter: n_estimator
테스트 정확도 평균 :  0.4210146516112633

In [10]:
dn_test = pd.read_csv("../byun/data/dinner_test_encoding.csv", encoding="utf-8")
dn_test

,datetime,year,month,date,worker_number,real_number,vacation_number,biztrip_number,overtime_number,telecom_number,...,season_winter,weekdays_friday,weekdays_monday,weekdays_thursday,weekdays_tuesday,weekdays_wednesday,vacation_N,vacation_Y,new_dinner_N,new_dinner_Y
0,2021-01-27,2021,1,27,2983,2355.0,88,182,5,358.0,...,1,0,0,0,0,1,1,0,0,1
1,2021-01-28,2021,1,28,2983,2319.0,104,212,409,348.0,...,1,0,0,1,0,0,1,0,1,0
2,2021-01-29,2021,1,29,2983,2170.0,270,249,0,294.0,...,1,1,0,0,0,0,1,0,1,0
3,2021-02-01,2021,2,1,2924,2340.0,108,154,538,322.0,...,1,0,1,0,0,0,1,0,1,0
4,2021-02-02,2021,2,2,2924,2362.0,62,186,455,314.0,...,1,0,0,0,1,0,1,0,1,0
5,2021-02-03,2021,2,3,2924,2380.0,59,199,5,286.0,...,1,0,0,0,0,1,1,0,1,0
6,2021-02-04,2021,2,4,2924,2364.0,61,211,476,288.0,...,1,0,0,1,0,0,1,0,1,0
7,2021-02-05,2021,2,5,2924,2247.0,169,252,0,256.0,...,1,1,0,0,0,0,1,0,1,0
8,2021-02-08,2021,2,8,2924,2333.0,88,174,690,329.0,...,1,0,1,0,0,0,1,0,1,0
9,2021-02-09,2021,2,9,2924,2318.0,94,183,542,329.0,...,1,0,0,0,1,0,1,0,1,0
10,2021-02-10,2021,2,10,2924,2068.0,489,134,0,233.0,...,1,0,0,0,0,1,0,1,1,0
11,2021-02-15,2021,2,15,2924,2260.0,178,131,795,355.0,...,1,0,1,0,0,0,1,0,1,0
12,2021-02-16,2021,2,16,2924,2266.0,70,175,815,413.0,...,1,0,0,0,1,0,1,0,1,0
13,2021-02-17,2021,2,17,2924,2287.0,77,181,3,379.0,...,1,0,0,0,0,1,1,0,1,0
14,2021-02-18,2021,2,18,2924,2256.0,83,247,594,338.0,...,1,0,0,1,0,0,1,0,1,0
15,2021-02-19,2021,2,19,2924,2200.0,176,268,1,280.0,...,1,1,0,0,0,0,1,0,1,0
16,2021-02-22,2021,2,22,2924,2375.0,105,197,814,247.0,...,1,0,1,0,0,0,1,0,1,0
17,2021-02-23,2021,2,23,2924,2416.0,75,200,783,233.0,...,1,0,0,0,1,0,1,0,1,0
18,2021-02-24,2021,2,24,2924,2378.0,77,235,3,234.0,...,1,0,0,0,0,1,1,0,1,0
19,2021-02-25,2021,2,25,2924,2346.0,91,252,585,235.0,...,1,0,0,1,0,0,1,0,1,0
20,2021-02-26,2021,2,26,2924,2205.0,261,279,1,179.0,...,1,1,0,0,0,0,0,1,1,0
21,2021-03-02,2021,3,2,2975,2422.0,139,166,781,248.0,...,0,0,0,0,1,0,1,0,1,0
22,2021-03-03,2021,3,3,2975,2438.0,50,195,1,292.0,...,0,0,0,0,0,1,1,0,0,1
23,2021-03-04,2021,3,4,2975,2404.0,72,236,746,263.0,...,0,0,0,1,0,0,1,0,1,0
24,2021-03-05,2021,3,5,2975,2334.0,158,257,2,226.0,...,0,1,0,0,0,0,1,0,1,0
25,2021-03-08,2021,3,8,2975,2444.0,97,170,939,264.0,...,0,0,1,0,0,0,1,0,1,0
26,2021-03-09,2021,3,9,2975,2447.0,76,170,1003,282.0,...,0,0,0,0,1,0,1,0,1,0
27,2021-03-10,2021,3,10,2975,2448.0,71,185,1,271.0,...,0,0,0,0,0,1,1,0,1,0
28,2021-03-11,2021,3,11,2975,2398.0,93,223,609,261.0,...,0,0,0,1,0,0,1,0,1,0
29,2021-03-12,2021,3,12,2975,2243.0,241,240,0,251.0,...,0,1,0,0,0,0,1,0,1,0
30,2021-03-15,2021,3,15,2975,2387.0,126,148,864,314.0,...,0,0,1,0,0,0,1,0,1,0
31,2021-03-16,2021,3,16,2975,2324.0,74,176,658,401.0,...,0,0,0,0,1,0,1,0,1,0
32,2021-03-17,2021,3,17,2975,2322.0,90,192,4,371.0,...,0,0,0,0,0,1,1,0,1,0
33,2021-03-18,2021,3,18,2975,2287.0,106,231,520,351.0,...,0,0,0,1,0,0,1,0,0,1
34,2021-03-19,2021,3,19,2975,2201.0,253,255,0,266.0,...,0,1,0,0,0,0,1,0,1,0
35,2021-03-22,2021,3,22,2975,2326.0,133,166,707,350.0,...,0,0,1,0,0,0,1,0,1,0
36,2021-03-23,2021,3,23,2975,2339.0,82,205,688,349.0,...,0,0,0,0,1,0,1,0,1,0
37,2021-03-24,2021,3,24,2975,2340.0,87,234,0,314.0,...,0,0,0,0,0,1,1,0,1,0
38,2021-03-25,2021,3,25,2975,2300.0,118,260,441,297.0,...,0,0,0,1,0,0,1,0,1,0
39,2021-03-26,2021,3,26,2975,2169.0,311,266,0,229.0,...,0,1,0,0,0,0,1,0,1,0
40,2021-03-29,2021,3,29,2975,2358.0,121,178,660,318.0,...,0,0,1,0,0,0,1,0,1,0
41,2021-03-30,2021,3,30,2975,2381.0,83,198,625,313.0,...,0,0,0,0,1,0,1,0,1,0
42,2021-03-31,2021,3,31,2975,2355.0,86,217,0,317.0,...,0,0,0,0,0,1,1,0,1,0
43,2021-04-01,2021,4,1,2973,2326.0,88,256,394,303.0,...,0,0,0,1,0,0,1,0,1,0
44,2021-04-02,2021,4,2,2973,2202.0,275,272,0,224.0,...,0,1,0,0,0,0,1,0,1,0
45,2021-04-05,2021,4,5,2973,2343.0,125,174,704,331.0,...,0,0,1,0,0,0,1,0,1,0
46,2021-04-06,2021,4,6,2973,2363.0,76,170,636,364.0,...,0,0,0,0,1,0,1,0,1,0
47,2021-04-07,2021,4,7,2973,2329.0,96,214,1,334.0,...,0,0,0,0,0,1,1,0,1,0
48,2021-04-08,2021,4,8,2973,2306.0,105,238,509,324.0,...,0,0,0,1,0,0,1,0,1,0
49,2021-04-09,2021,4,9,2973,2217.0,259,268,0,229.0,...,0,1,0,0,0,0,1,0,1,0